participants:
  - el_type: geth
    el_image: jihoonsg/geth-eip7928:bals-off
    cl_type: prysm
    cl_image: jihoonsg/prysm-beacon-chain-eip7928:abd7710
    vc_type: prysm
    vc_image: jihoonsg/prysm-validator-eip7928:abd7710
    count: 2
network_params:
  genesis_delay: 20
  fulu_fork_epoch: 0
  gloas_fork_epoch: 1
  perfect_peerdas_enabled: true
  seconds_per_slot: 6
  num_validator_keys_per_node: 32
snooper_enabled: true
dora_params:
  image: ethpandaops/dora:eip7928-support
additional_services:
  - dora
  - tx_fuzz
  - spamoor
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
